# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en-US
title: Next Stop Design
email: valerio.fanelli@gmail.com
description: "Next Stop Design Jekyll theme"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://nextstopdesign.it" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Valerio Fanelli
  twitter: mancoquesto
  picture: https://api.adorable.io/avatars/285/johndoe.png
twitter_username: mancoquesto
logo: /assets/icons/basically-basic-logo-light.svg
search: true
search_full_content: true

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
theme: nextstop-theme
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections_dir: collections
collections:
  top-items:
    output: false
  projects:
    output: true
    permalink: /:collection/:path/
